service: items-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: v1
  region: ap-southeast-1


functions:
  hello:
    handler: handler.hello
